export const employees = [
  {
    id: 1,
    name: "Alice Johnson",
    designation: "Senior Software Engineer",
    contact: "alice.johnson@company.com",
    skills: ["React", "Node.js", "GraphQL", "TypeScript", "AWS"],
    years_of_experience: 6,
    date_of_joining: "2019-04-12",
    status: "active",
    current_project: "HRMS Portal",
    projects_worked_on: ["HRMS Portal", "Client Dashboard", "Payroll Management System"],
    occupancy: { "HRMS Portal": 80, "Client Dashboard": 15, "Payroll Management System": 5 },
    department: "Engineering",
    salary: 95000,
    performance_rating: 4.5,
    leave_balance: { annual: 15, sick: 8 },
    manager: "David Wilson"
  },
  {
    id: 2,
    name: "Carol Davis",
    designation: "DevOps Engineer",
    contact: "carol.davis@company.com",
    skills: ["Docker", "Kubernetes", "AWS", "Jenkins", "Terraform"],
    years_of_experience: 5,
    date_of_joining: "2020-08-15",
    status: "active",
    current_project: "Cloud Infrastructure Upgrade",
    projects_worked_on: ["Cloud Infrastructure Upgrade", "CI/CD Modernization", "Security Compliance Audit"],
    occupancy: { "Cloud Infrastructure Upgrade": 50, "CI/CD Modernization": 30, "Security Compliance Audit": 20 },
    department: "Engineering",
    salary: 88000,
    performance_rating: 4.7,
    leave_balance: { annual: 12, sick: 6 },
    manager: "David Wilson"
  },
  {
    id: 3,
    name: "David Wilson",
    designation: "Engineering Manager",
    contact: "david.wilson@company.com",
    skills: ["Team Leadership", "Project Management", "Java", "Python"],
    years_of_experience: 10,
    date_of_joining: "2018-01-20",
    status: "active",
    current_project: "Engineering Operations Oversight",
    projects_worked_on: ["Engineering Operations Oversight", "System Architecture Review", "Technical Hiring Drive"],
    occupancy: { "Engineering Operations Oversight": 60, "System Architecture Review": 25, "Technical Hiring Drive": 15 },
    department: "Engineering",
    salary: 120000,
    performance_rating: 4.8,
    leave_balance: { annual: 18, sick: 5 },
    manager: "CEO"
  },
  {
    id: 4,
    name: "Emma Brown",
    designation: "Frontend Developer",
    contact: "emma.brown@company.com",
    skills: ["React", "Vue.js", "JavaScript", "CSS", "HTML"],
    years_of_experience: 3,
    date_of_joining: "2022-03-01",
    status: "active",
    current_project: "Client Performance Dashboard",
    projects_worked_on: ["Client Performance Dashboard", "Corporate Landing Page"],
    occupancy: { "Client Performance Dashboard": 90, "Corporate Landing Page": 10 },
    department: "Engineering",
    salary: 65000,
    performance_rating: 4.1,
    leave_balance: { annual: 22, sick: 12 },
    manager: "David Wilson"
  },
  {
    id: 5,
    name: "Grace Lee",
    designation: "QA Engineer",
    contact: "grace.lee@company.com",
    skills: ["Selenium", "Jest", "Cypress", "Manual Testing", "API Testing"],
    years_of_experience: 3,
    date_of_joining: "2022-09-10",
    status: "active",
    current_project: "HRMS Portal",
    projects_worked_on: ["HRMS Portal", "Quality Validation Suite"],
    occupancy: { "HRMS Portal": 90, "Quality Validation Suite": 10 },
    department: "Engineering",
    salary: 60000,
    performance_rating: 4.4,
    leave_balance: { annual: 25, sick: 15 },
    manager: "David Wilson"
  },
  {
    id: 6,
    name: "Henry Taylor",
    designation: "Backend Developer",
    contact: "henry.taylor@company.com",
    skills: ["Node.js", "Python", "MongoDB", "PostgreSQL", "Redis"],
    years_of_experience: 5,
    date_of_joining: "2020-11-05",
    status: "active",
    current_project: "Core API Service Layer",
    projects_worked_on: ["Core API Service Layer", "Database Optimization Engine", "Microservice Migration"],
    occupancy: { "Core API Service Layer": 70, "Database Optimization Engine": 20, "Microservice Migration": 10 },
    department: "Engineering",
    salary: 82000,
    performance_rating: 4.6,
    leave_balance: { annual: 14, sick: 7 },
    manager: "David Wilson"
  },
  {
    id: 7,
    name: "Irene Clark",
    designation: "Full Stack Developer",
    contact: "irene.clark@company.com",
    skills: ["React", "Node.js", "Express", "PostgreSQL", "Docker"],
    years_of_experience: 4,
    date_of_joining: "2021-07-18",
    status: "freepool",
    current_project: null,
    projects_worked_on: ["E-Commerce Platform", "Internal Analytics Dashboard"],
    occupancy: { "E-Commerce Platform": 60, "Internal Analytics Dashboard": 25 },
    department: "Engineering",
    salary: 78000,
    performance_rating: 4.3,
    leave_balance: { annual: 20, sick: 10 },
    manager: "David Wilson"
  },
  {
    id: 8,
    name: "Jack Nguyen",
    designation: "Mobile App Developer",
    contact: "jack.nguyen@company.com",
    skills: ["React Native", "Expo", "JavaScript", "Firebase"],
    years_of_experience: 5,
    date_of_joining: "2021-03-25",
    status: "active",
    current_project: "HRMS Mobile Companion App",
    projects_worked_on: ["HRMS Mobile Companion App", "Customer Engagement App", "Field Service Agent App"],
    occupancy: { "HRMS Mobile Companion App": 65, "Customer Engagement App": 15, "Field Service Agent App": 20 },
    department: "Engineering",
    salary: 85000,
    performance_rating: 4.5,
    leave_balance: { annual: 18, sick: 9 },
    manager: "David Wilson"
  },
  {
    id: 9,
    name: "Kiran Patel",
    designation: "Backend Developer",
    contact: "kiran.patel@company.com",
    skills: ["Go", "PostgreSQL", "Redis", "Docker", "Kubernetes"],
    years_of_experience: 6,
    date_of_joining: "2019-09-09",
    status: "freepool",
    current_project: null,
    projects_worked_on: ["Payment Gateway Service", "Event Stream Processor"],
    occupancy: { "Payment Gateway Service": 80, "Event Stream Processor": 15 },
    department: "Engineering",
    salary: 92000,
    performance_rating: 4.4,
    leave_balance: { annual: 14, sick: 6 },
    manager: "David Wilson"
  },
  {
    id: 10,
    name: "Liam Turner",
    designation: "Frontend Developer",
    contact: "liam.turner@company.com",
    skills: ["Next.js", "React", "Tailwind CSS", "Redux", "REST APIs"],
    years_of_experience: 3,
    date_of_joining: "2023-01-10",
    status: "active",
    current_project: "Marketing Analytics Portal",
    projects_worked_on: ["Marketing Analytics Portal"],
    occupancy: { "Marketing Analytics Portal": 100 },
    department: "Engineering",
    salary: 68000,
    performance_rating: 4.2,
    leave_balance: { annual: 21, sick: 8 },
    manager: "David Wilson"
  },
  {
    id: 11,
    name: "Maya Kapoor",
    designation: "Software Engineer",
    contact: "maya.kapoor@company.com",
    skills: ["Python", "Flask", "React", "PostgreSQL", "Docker"],
    years_of_experience: 4,
    date_of_joining: "2021-12-14",
    status: "freepool",
    current_project: null,
    projects_worked_on: ["Data Insights Portal", "Workflow Automation Engine"],
    occupancy: { "Data Insights Portal": 70, "Workflow Automation Engine": 20 },
    department: "Engineering",
    salary: 75000,
    performance_rating: 4.3,
    leave_balance: { annual: 17, sick: 9 },
    manager: "David Wilson"
  },
  {
    id: 12,
    name: "Noah Bennett",
    designation: "UI/UX Developer",
    contact: "noah.bennett@company.com",
    skills: ["Figma", "React", "Tailwind CSS", "Accessibility", "UI Design"],
    years_of_experience: 3,
    date_of_joining: "2023-05-10",
    status: "freepool",
    current_project: null,
    projects_worked_on: ["Design System Framework", "Website Redesign Initiative"],
    occupancy: { "Design System Framework": 50, "Website Redesign Initiative": 35 },
    department: "Engineering",
    salary: 70000,
    performance_rating: 4.1,
    leave_balance: { annual: 20, sick: 10 },
    manager: "David Wilson"
  },
  {
    id: 13,
    name: "Olivia Martin",
    designation: "Data Engineer",
    contact: "olivia.martin@company.com",
    skills: ["Python", "Airflow", "SQL", "ETL Pipelines", "AWS Glue"],
    years_of_experience: 5,
    date_of_joining: "2020-06-17",
    status: "freepool",
    current_project: null,
    projects_worked_on: ["Enterprise Data Warehouse", "Analytics Pipeline Migration"],
    occupancy: { "Enterprise Data Warehouse": 85, "Analytics Pipeline Migration": 10 },
    department: "Engineering",
    salary: 88000,
    performance_rating: 4.4,
    leave_balance: { annual: 16, sick: 8 },
    manager: "David Wilson"
  },
  {
    id: 14,
    name: "Paul Anderson",
    designation: "Backend Developer",
    contact: "paul.anderson@company.com",
    skills: ["Node.js", "Express", "GraphQL", "PostgreSQL", "Redis"],
    years_of_experience: 4,
    date_of_joining: "2021-09-05",
    status: "freepool",
    current_project: null,
    projects_worked_on: ["Unified API Gateway", "User Access Control System"],
    occupancy: { "Unified API Gateway": 75, "User Access Control System": 20 },
    department: "Engineering",
    salary: 80000,
    performance_rating: 4.2,
    leave_balance: { annual: 18, sick: 9 },
    manager: "David Wilson"
  },
  {
    id: 15,
    name: "Riya Sharma",
    designation: "QA Automation Engineer",
    contact: "riya.sharma@company.com",
    skills: ["Selenium", "Cypress", "Jenkins", "Playwright", "TestNG"],
    years_of_experience: 4,
    date_of_joining: "2021-11-01",
    status: "freepool",
    current_project: null,
    projects_worked_on: ["Automation Framework Suite", "Regression Test Repository"],
    occupancy: { "Automation Framework Suite": 65, "Regression Test Repository": 25 },
    department: "Engineering",
    salary: 72000,
    performance_rating: 4.3,
    leave_balance: { annual: 22, sick: 11 },
    manager: "David Wilson"
  },
  {
    id: 16,
    name: "Sahil Verma",
    designation: "DevOps Engineer",
    contact: "sahil.verma@company.com",
    skills: ["AWS", "Docker", "Kubernetes", "Terraform", "Linux"],
    years_of_experience: 5,
    date_of_joining: "2020-04-22",
    status: "freepool",
    current_project: null,
    projects_worked_on: ["Infrastructure Automation Platform", "Deployment Orchestration System"],
    occupancy: { "Infrastructure Automation Platform": 90, "Deployment Orchestration System": 5 },
    department: "Engineering",
    salary: 87000,
    performance_rating: 4.5,
    leave_balance: { annual: 15, sick: 7 },
    manager: "David Wilson"
  }   
];


export const projects = [
  {
    id: 1,
    name: "HRMS Portal",
    status: "active",
    start_date: "2024-01-15",
    end_date: "2024-06-30",
    team_size: 4,
    budget: 150000,
    client: "Internal",
    description: "Complete HR management system with employee tracking, payroll, and analytics"
  },
  {
    id: 2,
    name: "Client Dashboard",
    status: "active",
    start_date: "2024-02-01",
    end_date: "2024-05-15",
    team_size: 3,
    budget: 80000,
    client: "TechCorp Inc",
    description: "Real-time analytics dashboard for client data visualization"
  },
  {
    id: 3,
    name: "Infrastructure Upgrade",
    status: "active",
    start_date: "2024-01-01",
    end_date: "2024-04-30",
    team_size: 2,
    budget: 120000,
    client: "Internal",
    description: "Modernizing cloud infrastructure and implementing DevOps practices"
  }
];